### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by UlrichEckhardt** [davidkarlsen/bruno-image#3]
Hi David,

great initiative, thanks for making this start with Bruno in Docker packaging! 

Anyhow, I checked this out and was wondering how you are using the built image. I would normally mount a collection of tests as a volume into the container, but using the root directory (which is the `WORKDIR`) doesn't work. Are you using this as a base-image only or how do you use this?

I've forked the repo and set the `WORKDIR` to `/bruno`, which then allows running it with `docker run --rm --volume .:/bruno ...`. I also added a README and a bit of boilerplate. If you want to take a look, it's under https://github.com/UlrichEckhardt/bruno-image. It's not ready for a PR yet though and I first wanted to ask you about it anyway.

Have a great weekend!

Uli

**Comment by davidkarlsen** [comment]
we run it like this, using `docker-compose`:

```yaml
services:
  bruno:
    platform: linux/amd64
    image: ghcr.io/davidkarlsen/bruno-image:main
    pull_policy: always
    network_mode: host
    working_dir: /tests
    volumes:
    - ./refapp-domain-api/src/test/resources/bruno-api-smoketest:/tests
    environment:
      - BASE_URL
      - API_KEY
```
